# Generated by Django 5.0.3 on 2024-03-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='date_register',
            field=models.DateField(auto_now_add=True),
        ),
    ]
