# Generated by Django 5.0.3 on 2024-03-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_alter_receipts_date_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='date_register',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
