# Generated by Django 5.0.3 on 2024-03-22 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('receipts', '0003_alter_receipts_date_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='client',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name_fk', to='clients.client_register'),
        ),
    ]
